(define (problem jp3) (:domain hotel)
	(:objects
		h0 h1 h2 h3 h4 h5 - habitacion
		r0 r1 r2 r3 r4 r5 r6 r7 r8 - reserva
	)
	(:init
		(= (cantidad_reservas) 0)
		(= (xctj_ocupacion) 0)
		(= (start_day r0) 26)
		(= (start_day r1) 20)
		(= (start_day r2) 10)
		(= (start_day r3) 14)
		(= (start_day r4) 25)
		(= (start_day r5) 10)
		(= (start_day r6) 10)
		(= (start_day r7) 15)
		(= (start_day r8) 1)
		(= (end_day r0) 27)
		(= (end_day r1) 29)
		(= (end_day r2) 24)
		(= (end_day r3) 18)
		(= (end_day r4) 26)
		(= (end_day r5) 21)
		(= (end_day r6) 28)
		(= (end_day r7) 28)
		(= (end_day r8) 25)
		(= (tamano h0) 4)
		(= (tamano h1) 2)
		(= (tamano h2) 4)
		(= (tamano h3) 2)
		(= (tamano h4) 2)
		(= (tamano h5) 4)
		(= (tamano r0) 2)
		(= (tamano r1) 4)
		(= (tamano r2) 3)
		(= (tamano r3) 1)
		(= (tamano r4) 4)
		(= (tamano r5) 2)
		(= (tamano r6) 3)
		(= (tamano r7) 1)
		(= (tamano r8) 2)
	)
	(:goal (or (forall (?res - reserva) (visitada ?res))))
	(:metric maximize (+ (/ (xctj_ocupacion) (cantidad_reservas)) (/ (cantidad_reservas) 9)))
)
