(define (problem p2) (:domain hotel)
	(:objects
		h0 h1 - habitacion
		r0 r1 r2 r3 r4 r5 r6 r7 - reserva
	)
	(:init
		(= (reservas_libres) 8)
		(= (start_day r0) 13)
		(= (start_day r1) 29)
		(= (start_day r2) 8)
		(= (start_day r3) 7)
		(= (start_day r4) 1)
		(= (start_day r5) 27)
		(= (start_day r6) 21)
		(= (start_day r7) 18)
		(= (end_day r0) 24)
		(= (end_day r1) 30)
		(= (end_day r2) 9)
		(= (end_day r3) 10)
		(= (end_day r4) 8)
		(= (end_day r5) 30)
		(= (end_day r6) 29)
		(= (end_day r7) 22)
		(= (tamano h0) 4)
		(= (tamano h1) 1)
		(= (tamano r0) 2)
		(= (tamano r1) 4)
		(= (tamano r2) 2)
		(= (tamano r3) 4)
		(= (tamano r4) 1)
		(= (tamano r5) 1)
		(= (tamano r6) 2)
		(= (tamano r7) 3)
		(= (pref_orient_no_servida) 5)
		(= (orientacion h0) 2)
		(= (orientacion h1) 1)
		(= (orientacion r0) 3)
		(= (orientacion r1) 0)
		(= (orientacion r2) -1)
		(= (orientacion r3) 2)
		(= (orientacion r4) 0)
		(= (orientacion r5) -1)
		(= (orientacion r6) 1)
		(= (orientacion r7) -1)
	)
	(:goal (or (forall (?res - reserva) (visitada ?res))))
	(:metric minimize (+ (pref_orient_no_servida) (* (reservas_libres) 3)))
)