(define (problem p2) (:domain hotel)
	(:objects
		h0 h1 - habitacion
		r0 r1 r2 r3 r4 r5 r6 r7 - reserva
	)
	(:init
		(= (cantidad_reservas) 0)
		(= (xctj_ocupacion) 0)
		(= (start_day r0) 18)
		(= (start_day r1) 14)
		(= (start_day r2) 10)
		(= (start_day r3) 10)
		(= (start_day r4) 11)
		(= (start_day r5) 12)
		(= (start_day r6) 7)
		(= (start_day r7) 24)
		(= (end_day r0) 27)
		(= (end_day r1) 16)
		(= (end_day r2) 24)
		(= (end_day r3) 14)
		(= (end_day r4) 27)
		(= (end_day r5) 25)
		(= (end_day r6) 16)
		(= (end_day r7) 25)
		(= (tamano h0) 1)
		(= (tamano h1) 3)
		(= (tamano r0) 3)
		(= (tamano r1) 1)
		(= (tamano r2) 2)
		(= (tamano r3) 3)
		(= (tamano r4) 3)
		(= (tamano r5) 1)
		(= (tamano r6) 3)
		(= (tamano r7) 1)
	)
	(:goal (or (forall (?res - reserva) (visitada ?res))))
	(:metric maximize (+ (/ (xctj_ocupacion) (cantidad_reservas)) (/ (cantidad_reservas) 8)))
)