(define (problem nivel_basico) (:domain hotel)
    (:objects
    	h0 h1 - habitacion
    	r1 r2 r3 r4 r5 r6 r7 r8 r9 - reserva
        r12 r22 r32 r42 r52 r62 r72 r82 r92 - reserva
        d1 d2 d3 d4 d5 d6 d7 d8 d9 - dia
    )
    (:init
        (libre h0 d1)
        (libre h0 d2)
        (libre h0 d3)
        (libre h0 d4)
        (libre h0 d5)
        (libre h0 d6)
        (libre h0 d7)
        (libre h0 d8)
        (libre h0 d9)
        (libre h1 d1)
        (libre h1 d2)
        (libre h1 d3)
        (libre h1 d4)
        (libre h1 d5)
        (libre h1 d6)
        (libre h1 d7)
        (libre h1 d8)
        (libre h1 d9)
        (reservado r1 d1)
        (reservado r2 d2)
        (reservado r3 d3)
        (reservado r4 d4)
        (reservado r5 d5)
        (reservado r6 d6)
        (reservado r7 d7)
        (reservado r8 d8)
        (reservado r9 d9)
        (reservado r12 d1)
        (reservado r22 d2)
        (reservado r32 d3)
        (reservado r42 d4)
        (reservado r52 d5)
        (reservado r62 d6)
        (reservado r72 d7)
        (reservado r82 d8)
        (reservado r92 d9)
        ;(reservado r112 d1)
        (= (tamano_habitacion h0) 2)
        (= (tamano_habitacion h1) 1)
        (= (tamano_reserva r1) 1)
        (= (tamano_reserva r2) 1)
        (= (tamano_reserva r3) 1)
        (= (tamano_reserva r4) 1)
        (= (tamano_reserva r5) 1)
        (= (tamano_reserva r6) 1)
        (= (tamano_reserva r7) 1)
        (= (tamano_reserva r8) 1)
        (= (tamano_reserva r9) 1)
        (= (tamano_reserva r12) 2)
        (= (tamano_reserva r22) 2)
        (= (tamano_reserva r32) 2)
        (= (tamano_reserva r42) 2)
        (= (tamano_reserva r52) 2)
        (= (tamano_reserva r62) 2)
        (= (tamano_reserva r72) 2)
        (= (tamano_reserva r82) 2)
        (= (tamano_reserva r92) 2)
    )

    (:goal (or (forall (?res - reserva) (visitada ?res))))
)