(define (problem p2) (:domain hotel)
	(:objects
		h0 h1 - habitacion
		r0 r1 r2 r3 r4 r5 r6 r7 - reserva
	)
	(:init
		(= (cantidad_reservas) 0)
		(= (xctj_ocupacion) 0)
		(= (habitaciones_unused) 2)
		(= (start_day r0) 3)
		(= (start_day r1) 20)
		(= (start_day r2) 5)
		(= (start_day r3) 7)
		(= (start_day r4) 23)
		(= (start_day r5) 28)
		(= (start_day r6) 3)
		(= (start_day r7) 29)
		(= (end_day r0) 22)
		(= (end_day r1) 29)
		(= (end_day r2) 22)
		(= (end_day r3) 10)
		(= (end_day r4) 27)
		(= (end_day r5) 29)
		(= (end_day r6) 30)
		(= (end_day r7) 30)
		(= (tamano h0) 1)
		(= (tamano h1) 3)
		(= (tamano r0) 3)
		(= (tamano r1) 3)
		(= (tamano r2) 2)
		(= (tamano r3) 1)
		(= (tamano r4) 2)
		(= (tamano r5) 1)
		(= (tamano r6) 1)
		(= (tamano r7) 1)
	)
	(:goal (or (forall (?res - reserva) (visitada ?res))))
	(:metric maximize (+ (+ (/ (xctj_ocupacion) (cantidad_reservas)) (/ (habitaciones_unused) 2)) (/ (cantidad_reservas) 8)))
)