(define (problem p2) (:domain hotel)
	(:objects
		h0 h1 - habitacion
		r0 r1 r2 r3 r4 r5 r6 r7 - reserva
	)
	(:init
		(= (reservas_libres) 8)
		(= (start_day r0) 26)
		(= (start_day r1) 9)
		(= (start_day r2) 29)
		(= (start_day r3) 14)
		(= (start_day r4) 13)
		(= (start_day r5) 1)
		(= (start_day r6) 27)
		(= (start_day r7) 3)
		(= (end_day r0) 29)
		(= (end_day r1) 20)
		(= (end_day r2) 30)
		(= (end_day r3) 19)
		(= (end_day r4) 20)
		(= (end_day r5) 10)
		(= (end_day r6) 30)
		(= (end_day r7) 10)
		(= (tamano h0) 2)
		(= (tamano h1) 3)
		(= (tamano r0) 3)
		(= (tamano r1) 1)
		(= (tamano r2) 3)
		(= (tamano r3) 2)
		(= (tamano r4) 3)
		(= (tamano r5) 1)
		(= (tamano r6) 3)
		(= (tamano r7) 3)
	)
	(:goal (or (forall (?res - reserva) (visitada ?res))))
	(:metric minimize (reservas_libres))
)